# https://docs.gitlab.com/ee/user/project/pages/
# https://gitlab.com/pages/plain-html

image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - find public/site -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public/site -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public/site
  publish: public/site
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH