import java.io.File
import java.nio.file.Path
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.relativeTo

class Utils {
    val hostName = "https://dmitryratty.gitlab.io"

    val currentPath: Path = Path.of(System.getProperty("user.dir")).normalize().toRealPath()

    val projectDir: Path = if (currentPath.endsWith("ratty-public"))
        currentPath else currentPath.resolve("ratty-public")

    val resourcesDir: Path = projectDir.resolve("src/main/resources")

    val testResourcesDir: Path = projectDir.resolve("src/test/resources")
    val testAutogeneratedDir: Path = projectDir.resolve("src/test/resources/autogenerated")

    val pagesSrcDir: Path = resourcesDir.resolve("pages")

    val buildOutDir: Path = projectDir.resolve("public")

    fun textPagesInput(): Map<Path, File> {
        return pagesSrcDir.toFile().walk().filter { it.name.endsWith(".txt") }
            .map { it.toPath().relativeTo(pagesSrcDir) to it }.toMap()
    }

    fun splitToParagraphs(text: String): List<String> {
        return text.split("\n\n")
    }

    fun cleanupBuildDir() {
        val persistentFiles = emptyList<Path>()
        buildOutDir.listDirectoryEntries().forEach {
            if (!persistentFiles.contains(it)) it.toFile().deleteRecursively()
        }
    }

    fun splitParagraphToLines(paragraph: String): List<String> {
        return paragraph.split('\n')
    }

    fun isHyperlink(word: String): Boolean {
        // if (word.contains(" ")) throw IllegalStateException()
        return word.startsWith("http://") || word.startsWith("https://")
    }

    fun textPageInputToHtmlOutputFile(path: String): File {
        return buildOutDir.resolve("${path.removeSuffix("txt")}html").toFile()
    }
}