import java.io.File
import java.nio.file.Path
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.relativeTo

object Utils {
    val hostName = "https://dmitryratty.gitlab.io"

    val currentPath: Path = Path.of(System.getProperty("user.dir")).normalize().toRealPath()

    val projectDir: Path = if (currentPath.endsWith("ratty-public"))
        currentPath else currentPath.resolve("ratty-public")

    val resourcesDir: Path = projectDir.resolve("src/main/resources")

    val testResourcesDir: Path = projectDir.resolve("src/test/resources")
    val testAutogeneratedDir: Path = projectDir.resolve("src/test/resources/autogenerated")

    val srcPagesDir: Path = resourcesDir.resolve("pages")
    val srcPagesGeneratedDir = srcPagesDir.resolve("other/generated")

    val srcOtherDir: Path = resourcesDir.resolve("other")

    val buildOutDir: Path = projectDir.resolve("public")

    fun textPagesInput(): Map<Path, File> {
        return srcPagesDir.toFile().walk().filter { it.name.endsWith(".txt") }
            .map { it.toPath().relativeTo(srcPagesDir) to it }.toMap()
    }

    fun splitToParagraphs(text: String): MutableList<String> {
        return text.split("\n\n").toMutableList()
    }

    fun cleanupBuildDir() {
        val persistentFiles = emptyList<Path>()
        buildOutDir.listDirectoryEntries().forEach {
            if (!persistentFiles.contains(it)) it.toFile().deleteRecursively()
        }
    }

    fun splitParagraphToLines(paragraph: String): List<String> {
        return paragraph.split('\n')
    }

    fun isHyperlink(word: String): Boolean {
        // if (word.contains(" ")) throw IllegalStateException()
        return word.startsWith("http://") || word.startsWith("https://")
    }

    fun isPrime(n: Long): Boolean {
        // Corner case.
        if (n <= 1) {
            return false
        }
        // Check from 2 to n - 1.
        for (i in 2 until n) {
            if (n % i == 0L) {
                return false
            }
        }
        return true
    }
}